### ISSUE TITLE
SMK_downloader_thumbnail.R throws error when "data/images" doesn't exist

### ISSUE THREAD

**Issue by maxodsbjerg** [maxodsbjerg/AfkodKunsten#2]
SMK_downloader_thumbnail.R throws error when "data/images" doesn't exist - there is a dir.create-function in there, but et doesn't work.

**Comment by VictorHarbo** [comment]
Pull request #4 fixes this bug by creating the data-directory before creating the data/images directory. PR waits for @maxodsbjerg to review and merge.
